#!/bin/bash
# CUDA 编译与运行脚本 (通过 Docker 容器, 无需本地安装 CUDA Toolkit)
# 使用 nvidia/cuda:12.8.0-devel-ubuntu22.04 镜像 (包含 CUDA 12.8 + nvcc)
#
# 用法:
#   ./cuda-docker make         编译
#   ./cuda-docker run <prog>   运行指定程序
#   ./cuda-docker all          编译并运行所有
#   ./cuda-docker shell        进入容器的 bash

IMAGE="nvidia/cuda:12.8.0-devel-ubuntu22.04"
CODE_DIR="$(cd "$(dirname "$0")" && pwd)"

case "${1:-all}" in
    make)
        docker run --rm --gpus all \
            -v "$CODE_DIR:/code" -w /code \
            --entrypoint /bin/bash \
            "$IMAGE" -c "make clean && make all"
        ;;
    run)
        shift
        docker run --rm --gpus all \
            -v "$CODE_DIR:/code" -w /code \
            --entrypoint /bin/bash \
            "$IMAGE" -c "./${1:-device_query}"
        ;;
    profile)
        shift
        docker run --rm --gpus all \
            -v "$CODE_DIR:/code" -w /code \
            --entrypoint /bin/bash \
            "$IMAGE" -c "make profile"
        ;;
    all)
        docker run --rm --gpus all \
            -v "$CODE_DIR:/code" -w /code \
            --entrypoint /bin/bash \
            "$IMAGE" -c "make clean && make all && make run"
        ;;
    shell)
        docker run -it --rm --gpus all \
            -v "$CODE_DIR:/code" -w /code \
            --entrypoint /bin/bash \
            "$IMAGE"
        ;;
    *)
        echo "Usage: $0 {make|run|profile|all|shell}"
        ;;
esac
